### My version of the exercices on the 1st chapter of the book: "Pandas 1.x Cookbook" (Harrison & Petrou).

In [111]:
import os
os.listdir('../input/pandas-cookbook-data')

['data']

In [112]:
import pandas as pd
import numpy as np

### 1 - Reading the dataset and storing it in a DataFrame:

In [113]:
movies = pd.read_csv("../input/pandas-cookbook-data/data/movie.csv") # optional attribute: index_col="movie_title"
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 2 - Acessing the 3 components of a DataFrame: `index`, `columns` and `data`:

In [114]:
columns = movies.columns # accessing the columns
index = movies.index # accessing the index
data = movies.values # data stores a numpy.ndarray

In [115]:
type(movies)

pandas.core.frame.DataFrame

In [116]:
print(type(columns)) # `columns` is of the `Index` type.
columns

<class 'pandas.core.indexes.base.Index'>

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [117]:
print(type(index)) # `index` is of the `RangeIndex` type
index
# the RangeIndex is similar to the python's built-in range()

<class 'pandas.core.indexes.range.RangeIndex'>

RangeIndex(start=0, stop=4916, step=1)

In [118]:
print(type(data)) # `data` is an numpy.ndarray
data

<class 'numpy.ndarray'>

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

"The index and the columns are closely related. Both of them are subclasses of `Index`. This allows me to perform similar operations on both the `index` and the `columns`":

In [119]:
print(issubclass(pd.RangeIndex, pd.Index))
print(issubclass(columns.__class__, pd.Index))

True
True

In [120]:
index.to_numpy()

array([   0,    1,    2, ..., 4913, 4914, 4915])

In [121]:
columns.to_numpy()

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

In [122]:
movies.to_numpy()

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

### 3 - Understanding data types:

In [123]:
# The `.dtypes` attribute returns a pandas Series if I need to use the data
print(type(movies.dtypes))
movies.dtypes # shows the column names along with its data type

<class 'pandas.core.series.Series'>

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [124]:
movies.dtypes.value_counts()

float64    13
object     12
int64       3
dtype: int64

In [125]:
movies.info() # provides more information than the previous ones

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   object
 1   director_name              4814 non-null   object
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object
 10  actor_1_name               4909 non-null   object
 11  movie_title                4916 non-null   object
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   object
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   object
 17  movie_imdb_link            4916 non-null   object
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4904 non-null   object
 20  country                    4911 non-null   object
 21  content_rating             4616 non-null   object
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [126]:
type(np.nan) # NaN is float for pandas and NumPy, pandas rely heavily on NumPy...

float

In [127]:
pd.Series(["1",np.nan,"3"]).dtype # 'O' is relative to `object`, if the comlumns has mixed values, its type is `object`

dtype('O')

#### Almost all pandas data types are built from NumPy

### 4 - Selecting a Column:
Selecting a column returns a `Series`:

In [128]:
print(type(movies['director_name']))
movies['director_name']

<class 'pandas.core.series.Series'>

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

... alternative way ...

In [129]:
print(type(movies.director_name))
movies.director_name

<class 'pandas.core.series.Series'>

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

We can also index off the `.loc`(by column name) and `.iloc`(by position) attributes to pull out a `Series`:

In [130]:
movies.loc[0:3, "director_name"] # if I want to get all the rows I should put just `:` (a Colon)

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
Name: director_name, dtype: object

In [131]:
movies.iloc[0:3, 1]

0     James Cameron
1    Gore Verbinski
2        Sam Mendes
Name: director_name, dtype: object

In [132]:
# the RangeIndex is similar to the python's built-in range()
movies["director_name"].index # returns a 'pandas.core.indexes.range.RangeIndex'

RangeIndex(start=0, stop=4916, step=1)

In [133]:
movies["director_name"].dtype # returns a 'numpy.dtype'

dtype('O')

In [134]:
movies["director_name"].size # returns a python `int`

4916

In [135]:
movies["director_name"].name #returns a python `str`

'director_name'

In [136]:
print(type(movies["director_name"].index))
print(type(movies["director_name"].dtype))
print(type(movies["director_name"].size))
print(type(movies["director_name"].name))

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'numpy.dtype'>
<class 'int'>
<class 'str'>

We can use the `.apply` method with the type function to get back a `Series` that has the type of every member. Rather than looking at the whole `Series` result, we will chain the `.unique` method onto the result, to look at just the unique types that are found in the `director_name` column:

In [137]:
#apply() is used for applying a function on the values of a Series, or applying a function along the axis of a DataFrame.
print(type(movies["director_name"].apply(type)))
movies["director_name"].apply(type) # this way we are applying the type function along the values of the series...

<class 'pandas.core.series.Series'>

0         <class 'str'>
1         <class 'str'>
2         <class 'str'>
3         <class 'str'>
4         <class 'str'>
             ...
4911      <class 'str'>
4912    <class 'float'>
4913      <class 'str'>
4914      <class 'str'>
4915      <class 'str'>
Name: director_name, Length: 4916, dtype: object

In [138]:
# .unique() Return unique values of Series object.
movies["director_name"].apply(type).unique()

array([<class 'str'>, <class 'float'>], dtype=object)

### 5 - Calling Series Methods:
We can use the built-in `dir()` function to uncover all the attributes and methods of a `Series`:

In [139]:
dir(pd.Series) ## returns a `list` with all the Series attributes and methods
series_attributes_and_methods = set(dir(pd.Series)) ## returns a `set` with all the Series attributes and methods
print("Quantity of Series Attributes and Methods:", len(series_attributes_and_methods))

Quantity of Series Attributes and Methods: 433

In [140]:
dir(pd.DataFrame)
dataframe_attributes_and_methods = set(dir(pd.DataFrame))
print("Quantity of DataFrame Attributes and Methods:", len(dataframe_attributes_and_methods))

Quantity of DataFrame Attributes and Methods: 430

In [141]:
s = series_attributes_and_methods
d = dataframe_attributes_and_methods
print("How many Attributes and Methods they both have in common:", len(s & d))

How many Attributes and Methods they both have in common: 377

`.dtype`:

In [142]:
director = movies["director_name"]
fb_likes = movies["actor_1_facebook_likes"]

In [143]:
director.dtype

dtype('O')

In [144]:
fb_likes.dtype

dtype('float64')

`.head()` and `sample()`:

In [145]:
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [146]:
director.sample(n=5, random_state=42)

2347      Brian Percival
4687         Lucio Fulci
691        Phillip Noyce
3911       Sam Peckinpah
2488    Rowdy Herrington
Name: director_name, dtype: object

`.value_counts()`:

In [147]:
director.value_counts()

Steven Spielberg      26
Woody Allen           22
Martin Scorsese       20
Clint Eastwood        20
Spike Lee             16
                      ..
Liliana Cavani         1
Newt Arnold            1
Pascal Chaumeil        1
Leigh Whannell         1
Mariette Monpierre     1
Name: director_name, Length: 2397, dtype: int64

In [148]:
director.value_counts(normalize=True)

Steven Spielberg      0.005401
Woody Allen           0.004570
Martin Scorsese       0.004155
Clint Eastwood        0.004155
Spike Lee             0.003324
                        ...
Liliana Cavani        0.000208
Newt Arnold           0.000208
Pascal Chaumeil       0.000208
Leigh Whannell        0.000208
Mariette Monpierre    0.000208
Name: director_name, Length: 2397, dtype: float64

In [149]:
fb_likes.value_counts()

1000.0     436
11000.0    206
2000.0     189
3000.0     150
12000.0    131
          ...
362.0        1
216.0        1
859.0        1
225.0        1
334.0        1
Name: actor_1_facebook_likes, Length: 877, dtype: int64

`.size`, `.shape` and `.unique()`:

In [150]:
director.size

4916

In [151]:
director.shape

(4916,)

In [152]:
director.unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Scott Smith', 'Benjamin Roberds', 'Daniel Hsia'], dtype=object)

In [153]:
director.unique().size

2398

In [154]:
type(director.unique())

numpy.ndarray

`.count()`

In [155]:
director.count()

4814

In [156]:
fb_likes.count()

4909

`.min()`, `max()`, `mean()`, `.median()` and `std()`:

In [157]:
print("Min:", fb_likes.min())
print("Max:", fb_likes.max())
print("Mean:", fb_likes.mean())
print("Median:", fb_likes.median())
print("Std:", fb_likes.std())

Min: 0.0
Max: 640000.0
Mean: 6494.488490527602
Median: 982.0
Std: 15106.986883848309

.... or just use `.describe()`:

In [158]:
fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [159]:
director.describe()

count                 4814
unique                2397
top       Steven Spielberg
freq                    26
Name: director_name, dtype: object

`.quantile()`:

In [160]:
fb_likes.quantile(0.5)

982.0

In [161]:
fb_likes.quantile([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99])

0.10      240.0
0.20      510.0
0.30      694.0
0.40      854.0
0.50      982.0
0.60     1000.0
0.70     8000.0
0.80    13000.0
0.90    18000.0
0.95    23000.0
0.99    44920.0
Name: actor_1_facebook_likes, dtype: float64

`.isna()`:

In [162]:
director.isna()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

`fillna()`:

In [163]:
fb_likes_filled = director.fillna(0)
fb_likes_filled

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                    0
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [164]:
print(fb_likes.count())
print(fb_likes_filled.count())

4909
4916

`.dropna()`:

In [165]:
fb_likes_dropped = fb_likes.dropna()
print(fb_likes.size)
print(fb_likes_dropped.size)

4916
4909

`.hasnans`

In [166]:
print(director.hasnans)
print(fb_likes.hasnans)
print(fb_likes_filled.hasnans)
print(fb_likes_dropped.hasnans)

True
True
False
False

`.notna()`, which is the compliment of `.isna()`:

In [167]:
director.notna()

0        True
1        True
2        True
3        True
4        True
        ...
4911     True
4912    False
4913     True
4914     True
4915     True
Name: director_name, Length: 4916, dtype: bool

### 6 - Series Operations:

In [168]:
imdb_score = movies['imdb_score']
imdb_score

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
4911    7.7
4912    7.5
4913    6.3
4914    6.3
4915    6.6
Name: imdb_score, Length: 4916, dtype: float64

In [169]:
imdb_score + 10

0       17.9
1       17.1
2       16.8
3       18.5
4       17.1
        ...
4911    17.7
4912    17.5
4913    16.3
4914    16.3
4915    16.6
Name: imdb_score, Length: 4916, dtype: float64

The other basic arithmetic operators, minus (-), multiplication (*), division (/), and exponentiation (***) work similarly with scalar values.

In [170]:
imdb_score > 7

0        True
1        True
2       False
3        True
4        True
        ...
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

In [171]:
director == "James Cameron"

0        True
1       False
2       False
3       False
4       False
        ...
4911    False
4912    False
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [172]:
(director == "James Cameron").to_numpy().sum()

7

Each operator has an equivalent method(`.add()`, `.sub()`, `.mul()`, `.div()`, `.florrdiv()`, `.mod()`, `.pow()` and `.lt()`, `.gt()`, `.le()`, `.ge()`, `.eq()`, `.ne()`), for example:

In [173]:
imdb_score.add(10) # plus 1

0       17.9
1       17.1
2       16.8
3       18.5
4       17.1
        ...
4911    17.7
4912    17.5
4913    16.3
4914    16.3
4915    16.6
Name: imdb_score, Length: 4916, dtype: float64

In [174]:
imdb_score.gt(7) # greater than 7

0        True
1        True
2       False
3        True
4        True
        ...
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

### 7 - Chaining Series Methods:

In [175]:
director.value_counts().head(3)

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Name: director_name, dtype: int64

A common way to count the number of missing values:

In [176]:
fb_likes.isna().sum()

7

In [177]:
fb_likes.fillna(0).astype(int).head(4)

0     1000
1    40000
2    11000
3    27000
Name: actor_1_facebook_likes, dtype: int64

But chaining can make it difficult to debug.. but I can chain like this:

In [178]:
(fb_likes
 .fillna(0)
 .astype(int).head(4))

0     1000
1    40000
2    11000
3    27000
Name: actor_1_facebook_likes, dtype: int64

... or ...

In [179]:
fb_likes\
.fillna(0)\
.astype(int).head(4)

0     1000
1    40000
2    11000
3    27000
Name: actor_1_facebook_likes, dtype: int64

Another option for debugging a chain is to use the `.pipe()` method to show an intermediate valuee:

In [180]:
def print_bosta(series):
    print("bosta") #this is just for me to see that the chain has come to this point
    print(series)
    return series

fb_likes.fillna(0).pipe(print_bosta).astype(int).pipe(print_bosta).head(4)

bosta
0        1000.0
1       40000.0
2       11000.0
3       27000.0
4         131.0
         ...
4911      637.0
4912      841.0
4913        0.0
4914      946.0
4915       86.0
Name: actor_1_facebook_likes, Length: 4916, dtype: float64
bosta
0        1000
1       40000
2       11000
3       27000
4         131
        ...
4911      637
4912      841
4913        0
4914      946
4915       86
Name: actor_1_facebook_likes, Length: 4916, dtype: int64

0     1000
1    40000
2    11000
3    27000
Name: actor_1_facebook_likes, dtype: int64

### 8 - Renaming Column Names:

In [181]:
col_map = {
    "director_name": "director",
    "num_critic_for_reviews": "critic_reviews",
}

movies.rename(columns=col_map).head() # it returns a DataFrame with its columns renamed, but it doesn't change the original DataFrame

,color,director,critic_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [182]:
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

.. We can change the index also..

In [183]:
idx_map = {
    "Avatar": "Ratava",
    "Spectre": "Ertceps",
    "Pirates of the Caribbean: At World's End": "POC", 
}
col_map = {
    "aspect_ratio": "aspect",
    "movie_facebook_likes": "fblikes",
    "director_name": "director",
    "num_critic_for_reviews": "critic_reviews",
    "director_facebook_likes": "director_fblikes",
    "actor_3_facebook_likes": "actor_3_fblikes",
    "actor_1_facebook_likes": "actor_1_fblikes",
}

(
    movies.set_index("movie_title")
    .rename(index=idx_map, columns=col_map)
    .head(7)
)

,color,director,critic_reviews,duration,director_fblikes,actor_3_fblikes,actor_2_name,actor_1_fblikes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect,fblikes
movie_title,,,,,,,,,,,,,,,,,,,,,
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
John Carter,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
Spider-Man 3,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0

In [184]:
movies_idx = pd.read_csv("../input/pandas-cookbook-data/data/movie.csv", index_col="movie_title")
movies_idx

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
A Plague So Pleasant,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Shanghai Calling,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
My Date with Drew,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

... pulling the `index` and `columns` then putting in a `list`:

In [185]:
ids_list = movies_idx.index.to_list()
ids_list

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'Star Wars: Episode VII - The Force Awakens',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz the Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALL·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs. Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Godzilla Resurgence',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet 2',
 'The Incredible Hulk',
 'Miami Vice',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Harry Potter and the Deathly Hallows: Part II',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Sorcerer's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Harry Potter and the Deathly Hallows: Part I',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X-Men 2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 'The A-Team',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 '10,000 B.C.',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard with a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker in 3D',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Hannibal',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs: The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Daredevil',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'Déjà Vu',
 'Hotel Transylvania 2',
 'Bewitched',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking with Dinosaurs 3D',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Constantine',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Life',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Sleepy Hollow',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'Last Man Standing',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les Misérables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'The Missing',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Littleman',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'Rules of Engagement',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield 2',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'Xi you ji zhi: Sun Wukong san da Baigu Jing',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Sabrina, the Teenage Witch',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 'Sex and the City',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'Anger Management',
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Stargate SG-1',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'Alien 3',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! Band of Misfits',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Æon Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'Eye See You',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire: The Vampire Chronicles',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',

In [186]:
cols_list = movies_idx.columns.to_list()
cols_list

['color',
 'director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

... modifying them and putting them back to the DataFrame:

In [187]:
ids_list[0] = "Ratava"
ids_list[1] = "POC"
ids_list[2] = "Ertceps"

cols_list[1] = "d i r e c t o r"
cols_list[-2] = "aspect"
cols_list[-1] = "fblikes"

movies_idx.index = ids_list
movies_idx.columns = cols_list

movies_idx.head(3)

,color,d i r e c t o r,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect,fblikes
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

**it is possible to pass a function to the `.rename()` method:**

In [188]:
def to_clean(string):
    return string.strip().lower().replace(" ", "_") ## this is a good way to put all the names more in accordance with python attributes requirements..
movies_idx.rename(columns=to_clean)

,color,d_i_r_e_c_t_o_r,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect,fblikes
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
A Plague So Pleasant,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
Shanghai Calling,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
My Date with Drew,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

... or I can use comprehensions:

In [189]:
cols = [
    col.strip().lower().replace(" ", "_")
    for col in movies_idx.columns
]
cols
movies_idx.columns = cols
movies_idx.head()

,color,d_i_r_e_c_t_o_r,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect,fblikes
Ratava,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
POC,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Ertceps,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

### 9 - Creating and Deleting Columns:

In [190]:
movies["has_seen"] = 0
movies.head(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0

... or use the `.assign()` method to create a new column:

In [191]:
movies.assign(bosta=1) ## it does not mutate the original DataFrame...

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,bosta
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,1
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,1
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,1
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,1
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,1
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,1
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,1
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,1
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,1

adding up all columns that has facebook likes count:

In [192]:
total = ( # the plus operator does not ignores missing numbers, it will return NaN if it has to sum NaN with some valid number...
    movies.actor_1_facebook_likes
    + movies.actor_2_facebook_likes
    + movies.actor_3_facebook_likes
    + movies.director_facebook_likes
)
print(type(total))
total.head() ## Has missing numbers: NaN

<class 'pandas.core.series.Series'>

0     2791.0
1    46563.0
2    11554.0
3    95000.0
4        NaN
dtype: float64

In [193]:
movies.assign(total_likes=total) # this is one way of adding that Series to the DataFrame

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,total_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,2791.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,46563.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,11554.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,95000.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,1427.0
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,NaN
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,0.0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,2154.0
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,141.0

... another way ...

In [194]:
cols = [
    "actor_1_facebook_likes",
    "actor_2_facebook_likes",
    "actor_3_facebook_likes",
    "director_facebook_likes"
]

def print_type(obj):
    print(type(obj)) # I did this to find out that movies.loc[:, cols] is a DataFrame
    return obj

sum_col = movies.loc[:, cols].pipe(print_type).sum(axis="columns") # I could have just used movies.[cols] to select.
sum_col.head()                                                     # the .sum() method ignores the missing number (NaN).
                                                                   # .sum() converts NaN to 0.

<class 'pandas.core.frame.DataFrame'>

0     2791.0
1    46563.0
2    11554.0
3    95000.0
4      274.0
dtype: float64

In [195]:
movies.assign(total_likes=sum_col)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,total_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,2791.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,46563.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,11554.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,95000.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,1427.0
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,1753.0
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,0.0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,2154.0
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,141.0

**it is possible to pass a function to the `.assign()` method also:**

In [196]:
def sum_likes(df):
    return df[
        [ ## this is a good way of doing filtering ...
            c
            for c in df.columns
            if "like" in c
            and ("actor" in c or "director" in c)
        ]
    ].sum(axis=1)

movies.assign(total_likes=sum_likes) # passes `movies` as a parameter and returns a Series with the sum quantity, then append that Series to the DataFrame

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,total_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,2791.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,46563.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,11554.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,95000.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,1427.0
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,1753.0
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,0.0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,2154.0
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,141.0

Checking how many missing values there are in both `total` and `sum_col`: `total` was built using the + operator, and `sum_col` was built using the `.sum()` DataFrame method.

In [197]:
(
    movies.assign(total_likes=sum_col)["total_likes"]
    .isna()
    .sum()
)

0

In [198]:
(
    movies.assign(total_likes=total)["total_likes"]
    .isna()
    .sum()
)

122

In [199]:
# We could have filled in the missing values as well...
(
    movies.assign(total_likes=total.fillna(0))["total_likes"]
    .isna()
    .sum()
)

0

"There is another column in the dataset named `cast_total_facebook_likes`.
It would be interesting to see what percentage of this column comes from our newly
created column, `total_likes`. Before we create our percentage column, let's do
some basic data validation. We will ensure that `cast_total_facebook_likes`
is greater than or equal to `total_likes`:"

In [200]:
def cast_like_gt_actor(df):
    return (
        df["cast_total_facebook_likes"]
        >= df["total_likes"]
    )

df2 = movies.assign(
    total_likes = total,
    is_cast_likes_more=cast_like_gt_actor,
)
df2

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,total_likes,is_cast_likes_more
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,2791.0,True
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,46563.0,True
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,11554.0,True
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,95000.0,True
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,12.0,7.1,NaN,0,0,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,1427.0,True
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,NaN,False
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,0.0,True
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,2154.0,True
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,141.0,True

In [201]:
# Checking if all elements of the `is_cast_likes_more` column is True
df2["is_cast_likes_more"].all()

False

Using `.drop()` method to delete the `total_likes` column:

In [202]:
df2 = df2.drop(columns="total_likes")
df2

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen,is_cast_likes_more
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0,True
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0,True
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0,True
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,True
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0,True
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0,False
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0,True
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0,True
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0,True

In [205]:
# creating a Series of just total actor likes:
actor_sum = movies[
    [ ## filtering the columns
        c
        for c in movies.columns
        if "actor_" in c and "_likes" in c
    ]
].sum(axis="columns")
actor_sum.head()

0     2791.0
1    46000.0
2    11554.0
3    73000.0
4      143.0
dtype: float64

now chacking again...

In [208]:
print((movies["cast_total_facebook_likes"] >= actor_sum).all())
movies["cast_total_facebook_likes"] >= actor_sum

True

0       True
1       True
2       True
3       True
4       True
        ...
4911    True
4912    True
4913    True
4914    True
4915    True
Length: 4916, dtype: bool

... or ...

In [209]:
print(movies["cast_total_facebook_likes"].ge(actor_sum).all())
movies["cast_total_facebook_likes"].ge(actor_sum)

True

0       True
1       True
2       True
3       True
4       True
        ...
4911    True
4912    True
4913    True
4914    True
4915    True
Length: 4916, dtype: bool

"Finally, let's calculate the percentage of the `cast_total_facebook_likes` that come from `actor_sum`:"

In [212]:
pct_like = (
    actor_sum
    .div(movies["cast_total_facebook_likes"])
    .mul(100)
)
pct_like.describe()

count    4883.000000
mean       83.327889
std        14.056578
min        30.076696
25%        73.528368
50%        86.928884
75%        95.477440
max       100.000000
dtype: float64

In [213]:
pd.Series(
    pct_like.to_numpy(), index=movies["movie_title"]
).head()

movie_title
Avatar                                         57.736864
Pirates of the Caribbean: At World's End       95.139607
Spectre                                        98.752137
The Dark Knight Rises                          68.378310
Star Wars: Episode VII - The Force Awakens    100.000000
dtype: float64

Using `.insert()` and `.get_loc()`:

In [215]:
gross_index = movies.columns.get_loc("gross")
profit_index = gross_index + 1
profit_index

9

In [216]:
movies.insert( # the insert method modifies the original DataFrame, so there wont be a assignment statement.
    loc=profit_index,
    column="profit",
    value=movies["gross"] - movies["budget"]
)
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,profit,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,523505847.0,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,9404152.0,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,-44925825.0,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,198130642.0,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,NaN,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,NaN,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,NaN,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,NaN,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,84122.0,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0

An alternative to deleting columns with the `.drop` method is to use the `del` statement. This
also does not return a new DataFrame, so favor `.drop` over this:

In [217]:
del movies["director_name"]

In [219]:
# and to see that `director_names` has been deleted
movies

,color,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,profit,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,has_seen
0,Color,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,523505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,Color,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,9404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,Color,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,-44925825.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0
3,Color,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,198130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0
4,NaN,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,0
4912,Color,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,0
4913,Color,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,0
4914,Color,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,NaN,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,0
4915,Color,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,84122.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0